language: python
python:
 - "2.7"

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
 - pip install nose>=1.3.0
 - pip install coverage>=3.6
 - pip install coveralls
 - pip install numpy==1.9.2
 - pip install scipy==0.15.1
install:
 - travis_wait ./install

script:
 - ./run_tests
 - ./run_from_cmdline

after_success:
 - coveralls
