#!/bin/bash
#Install the packages needed for Scimage
if [[ "$OSTYPE" == "msys"* ]]; then
       echo "You are on a microsoft system. Please run the win_install.bat script instead"
else
	sudo apt-get update
	sudo apt-get install -y python-dev python-pip
	sudo apt-get install -y libpng-dev
	sudo apt-get install -y libfreetype6-dev libxft-dev
	python setup.py install
fi
