#!/bin/bash

set -e

mkdir -p log
test -e test/img && rm -r test/img
cp -r test/unburnable test/img
mkdir -p test/out/archive
mkdir -p test/out/timestreams
python -m exif2timestream -l log -d -c ./test/config.csv
rm -r test/out
